# Generated by Django 5.2.6 on 2025-09-08 08:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=9999999)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[(38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], default='not specified', max_length=20)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
    ]
