# Generated by Django 5.2.6 on 2025-09-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_store_size_remove_store_stock_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Store',
            new_name='Shoes',
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49')], max_length=2)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('shoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.shoes')),
            ],
            options={
                'unique_together': {('shoes', 'size')},
            },
        ),
        migrations.DeleteModel(
            name='StoreSize',
        ),
    ]
